### ISSUE TITLE
Tracer shows lots of warnings

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip#128]
Currently, the tracer shows a warning when a file-affecting syscall that is not handled is used by the experiment. However this means that a lot of warning can be printed when everything is actually fine (and warnings are scary!)

**Comment by fchirigati** [comment]
Maybe only show this on verbose mode? Or add this to a log file?

On Mon, Jul 13, 2015 at 12:28 PM, Remi Rampin <notifications@github.com>
wrote:

> Currently, the tracer shows a warning when a file-affecting syscall that
> is not handled is used by the experiment. However this means that a lot of
> warning can be printed when everything is actually fine (and warnings are
> scary!)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/issues/128>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Comment by remram44** [comment]
Yes, some of these might be moved from WARNING to INFO, but it's not entirely clear which.
