### ISSUE TITLE
Record CPU time

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip#149]
The C tracer could record the CPU time used by a process, by querying it when it execs, forks or dies.

Timing information might also be worth showing in the graph (this is already in the trace).

**Comment by remram44** [comment]
Also, write down walltime for a run in the config (next to exitcode), and show it in `reprounzip info`.

**Comment by remram44** [comment]
I have the code to record the walltime, is CPU time really useful? I can read it from `/proc/?/stat` if needed.

**Comment by julianafreire** [comment]
This may be useful for people reproducing the experiment; it may give guidance as to whether the task is compute-intensive.

**Comment by remram44** [comment]
I'm recording it then. It will be displayed for each run in the `reprounzip info` output, and could appear for each process in the graph once we have a better visualization.
