### ISSUE TITLE
Pack Debian packages?

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip#164]
During today's meeting somebody stated that unfortunately ReproZip only packs the files that are used, not the whole software packages. This is a feature and can certainly be changed.

It should be possible to choose to pack all the files from a package instead of only the ones that are accessed (make pack_files three-state? don't include these files/include these files/include whole package)

Getting all the .deb to setup the environment should also be possible (though we'd have to get dependencies?)

**Comment by fchirigati** [comment]
I think we should definitely add this feature, since it improves the reusability of the experiment. In this case, by default, we have the minimum necessary, and we could have, for instance, two flags (instead of a three-state variable): --no-packages (do not include software packages) and --full-packages (entire packages). Of course, both the latter and the default options should respect the configuration file (since users can select which packages they do not want to be included).

**Comment by remram44** [comment]
So these would be flags for `reprozip pack` that override the default for each package?

Also I'm not sure how to deal with the fact that .deb have dependencies on other .debs.

**Comment by fchirigati** [comment]
>
> So these would be flags for reprozip pack that override the default for
> each package?
>
Yes. But all the flags should respect the "packfiles" option in the
configuration file.

> Also I'm not sure how to deal with the fact that .deb have dependencies on
> other .debs.
>
You mean that it is hard to detect these dependencies? Or collect them?

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/issues/164#issuecomment-175175963>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Comment by remram44** [comment]
> You mean that it is hard to detect these dependencies? Or collect them?
>
Both... I don't want to dig into the full aptitude dependency graph.

**Comment by fchirigati** [comment]
Yes, it will be expensive to search for the dependencies. But if there is
no other option, the time spent on searching for these dependencies is a
price users need to pay if they want to use such feature.

On Tue, Jan 26, 2016 at 2:12 PM, Remi Rampin <notifications@github.com>
wrote:

> You mean that it is hard to detect these dependencies? Or collect them?
>
> Both... I don't want to dig into the full aptitude dependency graph.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/issues/164#issuecomment-175184589>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>
