### ISSUE TITLE
Improve References section in paper.md

### ISSUE THREAD

**Issue by stain** [ViDA-NYU/reprozip#226]
Hi, 

This is part of openjournals/joss-reviews#107

The [references here](https://github.com/ViDA-NYU/reprozip/blob/joss-paper/paper/paper.md#references) don't use DOIs where they should.

* `Archive on Zenodo` link should show and link to DOI  [doi:10.5281/zenodo.159604](https://doi.org/10.5281/zenodo.159604)
* https://github.com/ViDA-NYU/reprozip-examples should similarly be archived in Zenodo and given a DOI
* Is it possible to archive https://reprozip.readthedocs.io/en/1.0.x/ ? I believe it may be part of the `docs` folder of the existing Zenodo archive, but I'm not sure. I've added it to [web.archive.org](https://web.archive.org/web/20161110101921/https://reprozip.readthedocs.io/en/1.0.x/) - could you click-through to check all pages are there?
* "Most recent paper" should link to its [doi:10.1145/2882903.2899401](https://doi.org/10.1145/2882903.2899401)

Could you include authors and title for each of the references (in particular the paper)?  You don't need to go all classical journal style, just include the main authors (e.g. as shown in Zenodo). BTW, I like full name :-)

**Comment by remram44** [comment]
> https://github.com/ViDA-NYU/reprozip-examples should similarly be archived in Zenodo and given a DOI

We could register the OSF project, which has the GitHub project + the linked RPZ files (and the Vagrant machine).

> Is it possible to archive https://reprozip.readthedocs.io/en/1.0.x/ ? I believe it may be part of the docs folder of the existing Zenodo archive, but I'm not sure. I've added it to web.archive.org - could you click-through to check all pages are there?

The docs folder is indeed what the docs are built from, so that's archived.

**Comment by VickySteeves** [comment]
Hi @stain !! Thanks for the suggestions. I'll push the changes ASAP. 

> Archive on Zenodo link should show and link to DOI doi:10.5281/zenodo.159604

Done!

> https://github.com/ViDA-NYU/reprozip-examples should similarly be archived in Zenodo and given a DOI

We actually have a DOI of this via the [Open Science Framework](https://osf.io/8uxpv/registrations/). I will add this as soon as our last project administrator approves the registration.

> Is it possible to archive https://reprozip.readthedocs.io/en/1.0.x/ ? I believe it may be part of the docs folder of the existing Zenodo archive, but I'm not sure. I've added it to web.archive.org - could you click-through to check all pages are there?

The web.archive.org link doesn't actually have the pages, but as @remram44 said, it's archived with Zenodo. 

>"Most recent paper" should link to its doi:10.1145/2882903.2899401

Done!

> Could you include authors and title for each of the references (in particular the paper)? You don't need to go all classical journal style, just include the main authors (e.g. as shown in Zenodo). BTW, I like full name :-)

Done!

**Comment by VickySteeves** [comment]
Fixed [here](https://github.com/ViDA-NYU/reprozip/commit/e87965ac9d82601100d0f77d75e4bfabedc0c396).

**Comment by stain** [comment]
Thanks! You can close this issue.

**Comment by stain** [comment]
Perhaps including the Title as well as the author would be ideal.. but I'm satisfied with this.
