### ISSUE TITLE
Capture additional frontend files when packing web servers

### ISSUE THREAD

**Issue by remram44** [VIDA-NYU/reprozip#268]
Currently we can pack a webserver, allowing the server and application code to be reproduced to give access to the same dynamic website. However additional files needed by the client that don't come from the traced server (example: [content delivery networks](https://en.wikipedia.org/wiki/Content_delivery_network)) might change or not stay available, and though they don't interfere with the server, the web browser requires them for the user to be able to use the website.

It could be possible to download and pack those third-party files as well and reproduce the whole thing automatically.

This would help on our web use cases and is requested in our news app preservation effort.

What's needed:
* [ ] A crawler, web client that can hit several pages and download the files that do not come from the traced server.
* [ ] A server component to serve the additional files in reproduction
* [ ] Some proxy or mechanism to have the web pages reference the additional server instead of original file locations (possibly on long gone CDNs)
* [ ] An extension to the RPZ format to store the additional web archive in the same file

**Comment by remram44** [comment]
This is underway as a separate project!

**Comment by julianafreire** [comment]
@remram44 ACHE  could be used to crawl the site -- it supports crawling just within a site. Aecio could help you with this.
