### ISSUE TITLE
Uniformize logos

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip#289]
What is our official logo?

* App uses blue: https://github.com/ViDA-NYU/reprozip/blob/1.0.x/reprounzip-qt/reprounzip_qt/icon.png #256
* NYU purple versions exist
* New website theme uses inverted colors, with NYU purple: https://github.com/ViDA-NYU/reprozip/pull/275

Also there are "R", "RPZ", and "ReproZip" versions.

**Comment by remram44** [comment]
Thanks!

Now we have the issues that the colors don't match.

**Comment by VickySteeves** [comment]
Huh? All the logos on the OSF have the same color.

**Comment by VickySteeves** [comment]
Heng gave us the `.psd` in the OSF. 

yes, I mentioned the differences in logos above. This we should fix. 

The favicons are both NYU purple. We never had a blue logo so I'm not sure where you are getting that...

**Comment by remram44** [comment]
Icon currently used is [this](https://github.com/ViDA-NYU/reprozip/blob/1.0.x/reprounzip-qt/reprounzip_qt/icon.png), color is #6630cd. This I got directly from Heng and didn't alter.
The one you put [on OSF](https://osf.io/wt5uk/) has been changed to NYU purple (#57058b) by us, I remember us doing this. It shows obvious marks of a color change around the zipper.

Do you have the original from Heng (blue #6630cd) or is it lost?
