### ISSUE TITLE
Upgrade from platform.linux_distribution to distro

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip#314]
https://distro.readthedocs.io/

`platform.linux_distribution()` is deprecated in Python 3.5

**Comment by tirkarthi** [comment]
Removed in CPython master and will be released with Python 3.8 . Ref : https://bugs.python.org/issue28167

Thanks

**Comment by remram44** [comment]
Thanks for pointing that out! I will update to `distro` ASAP.
