### ISSUE TITLE
Update PyPI links to new domain

### ISSUE THREAD

**Issue by brainwane** [ViDA-NYU/reprozip#315]
Several links within the ReproZip website point to the old PyPI website, e.g., 

> https://pypi.python.org/pypi/reprounzip-vagrant

Those links do automatically redirect to the new PyPI site, e.g., 

> https://pypi.org/project/reprounzip-vagrant/ 

but I suggest you update to directly point to the new URLs.

You can replace `pypi.python.org` in your links with `pypi.org` and everything should just work. For instance, the project detail page `https://pypi.org/pypi/{name}` (with or without a trailing slash) redirects to `https://pypi.org/project/{name}/`. And, in cases where you want a shorter URL, `https://pypi.org/p/{name}/` will redirect to `https://pypi.org/project/{name}/`.

**Comment by remram44** [comment]
Good catch! Fixed by e8c50057.
