### ISSUE TITLE
hello world fails `reprounzip directory run` error

### ISSUE THREAD

**Issue by jwscook** [VIDA-NYU/reprozip#345]
Dear All,

I'm trying out a very simple use-case of reprozip, but doesn't work as expected. Below are the inputs, and steps that I performed, the expected behaviour, and my own conjecture on the failure. Finally, my version and os info.

**Experiment files**:

scripy.py
```
def hello_world():
    print("hello world")
if __name__ == "__main__":
    hello_world()
```

**What I did**

Then I run `reprozip trace python script.py`, where python is aliased to python 3:

```
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information
```

Then I execute:

1.  `reprozip pack example.rpz`.
2. `reprounzip directory setup example.rpz tmp`
3. `reprounzip directory run tmp` results in

```
/sbin/ldconfig.real: Can't stat /usr/local/cuda/lib64: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/local/lib/i386-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/local/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: /lib/i386-linux-gnu/ld-2.27.so is the dynamic linker, ignoring

/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.27.so is the dynamic linker, ignoring

/sbin/ldconfig.real: /lib32/ld-2.27.so is the dynamic linker, ignoring

/sbin/ldconfig.real: Cannot stat /usr/lib/libpyglib-2.0-python2.7.so: No such file or directory
hello world

*** Command finished, status: 0
```

**Expected behaviour**

`reprounzip directory run tmp` results in 

```
hello world
```

**Conjecture**

I'm surprised that 
```
$./tmp/root/usr/bin/python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

whereas the `python` that I ran during the `trace` stage is python 3 (see above).

Is this anything to do with the error?

**Info**

OS info:

```
$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

Reprozip version info:

```
$reprozip --version
reprozip version 1.0.16
$reprounzip --version
reprounzip version 1.0.16
```

**Comment by remram44** [comment]
Hi @jwscook, thanks for trying out ReproZip!

Aliases are only recognized by your shell. They don't kick in when you don't use them as the first word, e.g. `sudo python` would run Python 2, `watch python` would run Python 2, and similarly `reprozip trace python` runs Python 2. This is expected.

The output you see before the script's comes from ldconfig. It is weird that it shows so many warnings about your system's configuration, but it appears to be the same on my own Ubuntu... I've gone ahead and hidden those warnings since there's a lot and they are not interesting (39daea01, will be in next release).

-----

<details><summary>Re-running your experiment:</summary>

```
$ cat script.py
import sys

def hello_world():
    print("hello world")
    version = '.'.join(str(v) for v in sys.version_info)
    print("%s %s" % (sys.executable, version))
if __name__ == '__main__':
    hello_world()
```
```
$ reprozip trace python3 script.py
hello world
/usr/bin/python3 3.6.7.final.0
Configuration file written in .reprozip-trace/config.yml
Edit that file then run the packer -- use 'reprozip pack -h' for help
```
```
$ reprozip pack experiment.rpz
```
```
$ reprounzip directory setup experiment.rpz script/
```
```
$ reprounzip directory run script/
hello world
/tmp/script/root/usr/bin/python3 3.6.7.final.0

*** Command finished, status: 0
```

</details>

-----

Certainly looks better, thanks for the feedback!

**Comment by jwscook** [comment]
Thanks for your input.

Having run `reprozip trace /usr/bin/python3.6 script.py`, reprozip was able to gather up the right version of python.

Two follow up questions:

1) I installed reprozip via pip. Is there a mailing list I can sign up for information on new releases?
1) What markdown magic did you use to hide part of your post behind the arrow thing?

**Comment by remram44** [comment]
We don't announce new releases on a mailing-list, though I suppose we could. There is an Atom feed from GitHub: `https://github.com/ViDA-NYU/reprozip/tags.atom` or you can use libraries.io ([reprozip](https://libraries.io/pypi/reprozip) [reprounzip](https://libraries.io/pypi/reprounzip)).

The markdown magic is not really markdown, it is [the HTML `<details>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details), which is allowed by GitHub's markdown. Basically `<details><summary>Running the experiment:</summary> foobar...</details>` In practice I find that you need to drop a few extra newlines in and around those tags for it to render correctly, especially if code blocks are involved.
