### ISSUE TITLE
Need to run ReproUnzip-QT once on Linux to register it 

### ISSUE THREAD

**Issue by VickySteeves** [VIDA-NYU/reprozip#351]
We should add this to the docs, as it tripped me up when I went to do this today on Ubuntu 18.04 :sweat_smile:

**Comment by remram44** [comment]
Yes I removed the previous instructions but left that out (14031489). The only ways to install reprounzip-qt on Linux is through PIP or Conda right now, which do not allow me to do any setup during installation.
