### ISSUE TITLE
Build and publish Python 3.7 and 3.8 wheels

### ISSUE THREAD

**Issue by effigies** [VIDA-NYU/reprozip#362]
The latest wheel on PyPI is for Python 3.6. It would be nice to have wheels for more recent Pythons.

Follow-up to #224.

**Comment by remram44** [comment]
Ah yes. Good catch! Will do, if the manylinux machinery still works.

**Comment by remram44** [comment]
4d487179 fixes the build script.

I built `reprozip-1.0.16-cp38-cp38-manylinux2010_x86_64.whl` and uploaded it with Twine, however it is not showing up on pypi.org. Is it possible PyPI doesn't support it? Or maybe there is now a delay before it gets updated? (wasn't before)

**Comment by effigies** [comment]
Thanks. Any chance of 3.7?

**Comment by remram44** [comment]
Uploaded. This one appeared right away for some reason :thinking:

**Comment by effigies** [comment]
Thanks!
