### ISSUE TITLE
Broken Code of Conduct Link on Website

### ISSUE THREAD

**Issue by sachiniyer** [VIDA-NYU/reprozip#381]
I'm not sure if this is the right place for this, but I was scrolling through the [reprozip about page](https://www.reprozip.org/about.html) and found that the `CODE_OF_CONDUCT.md` link under **Contribute to Reprozip!** was broken.

The file seems to have been deleted in commit `1fadd26` by @remram44 with the Github community guidelines taking it's place.

I would submit a pull request but I can't seem to find the src.

**Comment by remram44** [comment]
Thanks Sachin! Fixed by f913e860
