### ISSUE TITLE
Keep track of input file status

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip#67]
@fchirigati notes that a pack might have input files that were not packed. In this case, they should be marked differently (not "(original)" as currently) and it shouldn't be possible to run the experiment before providing them (via 'upload').

**Comment by remram44** [comment]
Also, after a run which has some files as output, these files should be invalidated as input files (whatever you uploaded is not what is used, since that run wrote to them).

**Comment by julianafreire** [comment]
So do we have a versioning problem here? 
If a computation in the experiment wrote to the input file F_i, now we have a new file (a new version) F_o.
But to reproduce the experiment, we need F_i.
Maybe, we could flag  to the experiment creator all files that were read and written to in the experiment.

**Comment by fchirigati** [comment]
I think we are already flagging the user when a file is being read and
written in the same experiment (please correct me if I'm wrong, Remi
@remram44).
But we do not keep these different versions (or states) of the file (since
we copy files after tracing the experiment), so in this case, we cannot
guarantee reproducibility. To attain reproducibility, we would need to
store files while tracing (so as to identify when a file is about to
change).

On Tue, Aug 11, 2015 at 4:52 PM, Juliana Freire <notifications@github.com>
wrote:

> So do we have a versioning problem here?
> If a computation in the experiment wrote to the input file F_i, now we
> have a new file (a new version) F_o.
> But to reproduce the experiment, we need F_i.
> Maybe, we could flag to the experiment creator all files that were read
> and written to in the experiment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViDA-NYU/reprozip/issues/67#issuecomment-130068833>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>

**Comment by remram44** [comment]
The problem here is simply what the `showfiles` and `download` commands show. Once an file designated as input has been overridden by the reproducing user's version, these commands will show that in the list (with the pathname of the file that was uploaded). However, as you run the experiment, they can get overwritten again, in these commands could be aware of that.

Take this experiment, consisting of two separates steps that have been traced separately (with `trace --continue`):

    conffile   datafile
         |        |
         \/      \/
       ~ FIRST STEP ~
              |
              \/
        intermedarray
              |
              \/
      ~ SECOND STEP ~
              |
              \/
         graphfile

The user can replace 'intermedarray' with his own data, `myownarray.dat` to try the "second step" differently. There is no problem with this, and after running the second step, reprounzip will still display something like this:

    input files:
      - conffile: (original)
      - datafile: (original)
      - intermedarray: /home/reproducer/myownarray.dat

But then, running the first step will overwrite that intermediate file with the output from "first step". The "input files" list displayed by reprounzip should update to reflect that 'intermedarray' is not the reproducer's version of the file anymore.

I'll get this tomorrow.

**Comment by remram44** [comment]
On a separate note, there is no problem restoring 'intermedarray' or 'datafile' with the original version. So long as it was not omitted from the pack file, `upload :datafile` will do that.
